apiVersion: v1
kind: Service
metadata:
  name: {{ include "rust-sbc-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rust-sbc-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rust-sbc-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: control
      port: {{ .Values.service.controlPort }}
      targetPort: {{ .Values.service.controlTargetPort }}
      protocol: TCP
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: {{ .Values.service.wsTargetPort }}
      protocol: TCP
