"""Enable generated identity for invitation primary keys

Revision ID: 20260426_0003
Revises: 20260426_0002
Create Date: 2026-04-26 23:05:00.000000
"""

from alembic import op


revision = "20260426_0003"
down_revision = "20260426_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    if dialect_name == "oracle":
        op.execute(
            """
            ALTER TABLE invitation_codes
            MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))
            """
        )
        op.execute(
            """
            ALTER TABLE invitation_redemptions
            MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))
            """
        )
        return

    if dialect_name == "postgresql":
        # Postgres already created working defaults for these integer primary
        # keys during the original table creation path, so no follow-up change
        # is needed here.
        return


def downgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    if dialect_name == "oracle":
        op.execute(
            """
            ALTER TABLE invitation_redemptions
            MODIFY id DROP IDENTITY
            """
        )
        op.execute(
            """
            ALTER TABLE invitation_codes
            MODIFY id DROP IDENTITY
            """
        )
        return

    if dialect_name == "postgresql":
        return
